# Generated by Django 3.0.2 on 2020-03-21 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FDP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dept', models.CharField(default='Null', max_length=5)),
                ('des', models.TextField(max_length=300)),
                ('pdf', models.FileField(upload_to='upload')),
                ('points', models.IntegerField(default='0')),
                ('pointsaward', models.IntegerField(default='0')),
                ('user', models.CharField(default='AnonymousUser', max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='FDP2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dept', models.CharField(default='Null', max_length=5)),
                ('des', models.TextField(max_length=300)),
                ('pdf', models.FileField(upload_to='upload')),
                ('points', models.IntegerField(default='0')),
                ('pointsaward', models.IntegerField(default='0')),
                ('user', models.CharField(default='AnonymousUser', max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Grant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dept', models.CharField(default='Null', max_length=5)),
                ('des', models.TextField(max_length=300)),
                ('pdf', models.FileField(upload_to='upload')),
                ('points', models.IntegerField(default=0)),
                ('pointsaward', models.IntegerField(default='0')),
                ('user', models.CharField(default='AnonymousUser', max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='InterCollege',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dept', models.CharField(default='Null', max_length=5)),
                ('des', models.TextField(max_length=300)),
                ('pdf', models.FileField(upload_to='upload')),
                ('points', models.IntegerField(default='0')),
                ('pointsaward', models.IntegerField(default='0')),
                ('user', models.CharField(default='AnonymousUser', max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='InterCollege2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dept', models.CharField(default='Null', max_length=5)),
                ('des', models.TextField(max_length=300)),
                ('pdf', models.FileField(upload_to='upload')),
                ('points', models.IntegerField(default='0')),
                ('pointsaward', models.IntegerField(default='0')),
                ('user', models.CharField(default='AnonymousUser', max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='InternationalConf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dept', models.CharField(default='Null', max_length=5)),
                ('des', models.TextField(max_length=300)),
                ('pdf', models.FileField(upload_to='upload')),
                ('points', models.IntegerField(default='0')),
                ('pointsaward', models.IntegerField(default='0')),
                ('user', models.CharField(default='AnonymousUser', max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='InternationalConf2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dept', models.CharField(default='Null', max_length=5)),
                ('des', models.TextField(max_length=300)),
                ('pdf', models.FileField(upload_to='upload')),
                ('points', models.IntegerField(default='0')),
                ('pointsaward', models.IntegerField(default='0')),
                ('user', models.CharField(default='AnonymousUser', max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='NationalConf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dept', models.CharField(default='Null', max_length=5)),
                ('des', models.TextField(max_length=300)),
                ('pdf', models.FileField(upload_to='upload')),
                ('points', models.IntegerField(default='0')),
                ('pointsaward', models.IntegerField(default='0')),
                ('user', models.CharField(default='AnonymousUser', max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='NationalConf2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dept', models.CharField(default='Null', max_length=5)),
                ('des', models.TextField(max_length=300)),
                ('pdf', models.FileField(upload_to='upload')),
                ('points', models.IntegerField(default='0')),
                ('pointsaward', models.IntegerField(default='0')),
                ('user', models.CharField(default='AnonymousUser', max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Workshop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dept', models.CharField(default='Null', max_length=5)),
                ('des', models.TextField(max_length=300)),
                ('pdf', models.FileField(upload_to='upload')),
                ('points', models.IntegerField(default='0')),
                ('pointsaward', models.IntegerField(default='0')),
                ('user', models.CharField(default='AnonymousUser', max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Workshop2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dept', models.CharField(default='Null', max_length=5)),
                ('des', models.TextField(max_length=300)),
                ('pdf', models.FileField(upload_to='upload')),
                ('points', models.IntegerField(default='0')),
                ('pointsaward', models.IntegerField(default='0')),
                ('user', models.CharField(default='AnonymousUser', max_length=300)),
            ],
        ),
    ]
