# Generated by Django 3.0.2 on 2020-03-03 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skct', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academics',
            name='pdf',
            field=models.FileField(upload_to='upload'),
        ),
    ]
