# Generated by Django 3.0.2 on 2020-03-03 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skct', '0002_auto_20200303_1235'),
    ]

    operations = [
        migrations.AddField(
            model_name='academics',
            name='user',
            field=models.CharField(default='AnonymousUser', max_length=300),
        ),
    ]
