# Generated by Django 3.0.2 on 2020-03-03 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skct', '0003_academics_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proof',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('des', models.CharField(max_length=300)),
                ('pdf', models.FileField(upload_to='proof')),
                ('user', models.CharField(default='AnonymousUser', max_length=300)),
            ],
        ),
    ]
