# Generated by Django 3.0.2 on 2020-03-03 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skct', '0004_proof'),
    ]

    operations = [
        migrations.AddField(
            model_name='proof',
            name='act',
            field=models.CharField(default='NoActivitySpecified', max_length=300),
        ),
    ]
