# Generated by Django 3.0.2 on 2020-03-05 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skct', '0005_proof_act'),
    ]

    operations = [
        migrations.AddField(
            model_name='academics',
            name='points',
            field=models.IntegerField(default='0'),
        ),
    ]
