# Generated by Django 3.0.2 on 2020-03-10 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skct', '0007_academics_pointsaward'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=300)),
                ('name', models.CharField(default='', max_length=300)),
                ('dept', models.CharField(default='', max_length=300)),
                ('desig', models.CharField(default='', max_length=300)),
            ],
        ),
    ]
