# Generated by Django 3.0.2 on 2020-03-10 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skct', '0009_civil_cse_ece_eee_ice_it_mba_mech_sh'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Civil',
        ),
        migrations.DeleteModel(
            name='Cse',
        ),
        migrations.DeleteModel(
            name='Ece',
        ),
        migrations.DeleteModel(
            name='Eee',
        ),
        migrations.DeleteModel(
            name='Ice',
        ),
        migrations.DeleteModel(
            name='It',
        ),
        migrations.DeleteModel(
            name='Mba',
        ),
        migrations.DeleteModel(
            name='Mech',
        ),
        migrations.DeleteModel(
            name='Sh',
        ),
    ]
