# Generated by Django 3.0.2 on 2020-03-10 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skct', '0011_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
