# Generated by Django 3.0.2 on 2020-03-10 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skct', '0012_delete_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Profile',
            new_name='Staff',
        ),
    ]
