# Generated by Django 3.0.2 on 2020-03-10 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skct', '0014_auto_20200310_2232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proof',
            name='des',
            field=models.CharField(default='Null', max_length=300),
        ),
    ]
