# Generated by Django 3.0.2 on 2020-03-12 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skct', '0003_auto_20200214_2118'),
        ('skct', '0017_civil_cse_ece_eee_ice_it_mba_mech_sh'),
    ]

    operations = [
    ]
