# Generated by Django 3.0.2 on 2020-03-15 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skct', '0019_hod'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfDisplay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(default='AnonymousUser', max_length=300)),
            ],
        ),
    ]
