# Generated by Django 3.0.2 on 2020-03-18 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skct', '0023_allclear_article_awards_competitive_extracurricular_feedback_innovation_internship_onlinecertificati'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Academics',
        ),
        migrations.DeleteModel(
            name='AllClear',
        ),
        migrations.DeleteModel(
            name='Article',
        ),
        migrations.DeleteModel(
            name='Awards',
        ),
        migrations.DeleteModel(
            name='Competitive',
        ),
        migrations.DeleteModel(
            name='ExtraCurricular',
        ),
        migrations.DeleteModel(
            name='Feedback',
        ),
        migrations.DeleteModel(
            name='Innovation',
        ),
        migrations.DeleteModel(
            name='Internship',
        ),
        migrations.DeleteModel(
            name='OnlineCertification',
        ),
        migrations.DeleteModel(
            name='PG',
        ),
        migrations.DeleteModel(
            name='Prizes',
        ),
        migrations.DeleteModel(
            name='ProjectGuidance',
        ),
        migrations.DeleteModel(
            name='Startups',
        ),
        migrations.DeleteModel(
            name='StudentActivities',
        ),
        migrations.DeleteModel(
            name='ThreeClear',
        ),
        migrations.DeleteModel(
            name='UG',
        ),
    ]
