# Generated by Django 3.0.2 on 2020-03-21 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SelfDevelopment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='awards',
            name='pdf',
            field=models.FileField(upload_to='SelfDevelopmentAwards'),
        ),
        migrations.AlterField(
            model_name='events',
            name='pdf',
            field=models.FileField(upload_to='Events'),
        ),
        migrations.AlterField(
            model_name='eventsparticipation',
            name='pdf',
            field=models.FileField(upload_to='EventsParticipation'),
        ),
        migrations.AlterField(
            model_name='excellence',
            name='pdf',
            field=models.FileField(upload_to='Excellence'),
        ),
        migrations.AlterField(
            model_name='facultyattendance',
            name='pdf',
            field=models.FileField(upload_to='FacultyAttendance'),
        ),
        migrations.AlterField(
            model_name='guestlecture',
            name='pdf',
            field=models.FileField(upload_to='GuestLecture'),
        ),
        migrations.AlterField(
            model_name='guestlectureindustry',
            name='pdf',
            field=models.FileField(upload_to='GuestLectureIndustry'),
        ),
        migrations.AlterField(
            model_name='mou',
            name='pdf',
            field=models.FileField(upload_to='MOU'),
        ),
        migrations.AlterField(
            model_name='onlinecertification',
            name='pdf',
            field=models.FileField(upload_to='OnlineCertification'),
        ),
        migrations.AlterField(
            model_name='onlinecourse',
            name='pdf',
            field=models.FileField(upload_to='OnlineCourse'),
        ),
        migrations.AlterField(
            model_name='patentfiled',
            name='pdf',
            field=models.FileField(upload_to='PatentFiled'),
        ),
        migrations.AlterField(
            model_name='patentgranted',
            name='pdf',
            field=models.FileField(upload_to='PatentGranted'),
        ),
        migrations.AlterField(
            model_name='patentpublished',
            name='pdf',
            field=models.FileField(upload_to='PatentPublished'),
        ),
        migrations.AlterField(
            model_name='placementarranged',
            name='pdf',
            field=models.FileField(upload_to='PlacementArranged'),
        ),
    ]
