# Generated by Django 3.0.2 on 2020-03-21 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Applied',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('des', models.TextField(max_length=300)),
                ('pdf', models.FileField(upload_to='Article')),
                ('points', models.IntegerField(default='0')),
                ('pointsaward', models.IntegerField(default='0')),
                ('user', models.CharField(default='AnonymousUser', max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Consultancy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dept', models.CharField(default='Null', max_length=5)),
                ('des', models.TextField(max_length=300)),
                ('pdf', models.FileField(upload_to='Startups')),
                ('points', models.IntegerField(default='0')),
                ('pointsaward', models.IntegerField(default='0')),
                ('user', models.CharField(default='AnonymousUser', max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='DCM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dept', models.CharField(default='Null', max_length=5)),
                ('des', models.TextField(max_length=300)),
                ('pdf', models.FileField(upload_to='Awards')),
                ('points', models.IntegerField(default='0')),
                ('pointsaward', models.IntegerField(default='0')),
                ('user', models.CharField(default='AnonymousUser', max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='ESCI',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dept', models.CharField(default='Null', max_length=5)),
                ('des', models.TextField(max_length=300)),
                ('pdf', models.FileField(upload_to='Feedback')),
                ('points', models.IntegerField(default='0')),
                ('pointsaward', models.IntegerField(default='0')),
                ('user', models.CharField(default='AnonymousUser', max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Guideship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dept', models.CharField(default='Null', max_length=5)),
                ('des', models.TextField(max_length=300)),
                ('pdf', models.FileField(upload_to='StudentActivities')),
                ('points', models.IntegerField(default='0')),
                ('pointsaward', models.IntegerField(default='0')),
                ('user', models.CharField(default='AnonymousUser', max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='GuideshipPursuing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dept', models.CharField(default='Null', max_length=5)),
                ('des', models.TextField(max_length=300)),
                ('pdf', models.FileField(upload_to='Allclear')),
                ('points', models.IntegerField(default='0')),
                ('pointsaward', models.IntegerField(default='0')),
                ('user', models.CharField(default='AnonymousUser', max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='IEEE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dept', models.CharField(default='Null', max_length=5)),
                ('des', models.TextField(max_length=300)),
                ('pdf', models.FileField(upload_to='Extracurricular')),
                ('points', models.IntegerField(default='0')),
                ('pointsaward', models.IntegerField(default='0')),
                ('user', models.CharField(default='AnonymousUser', max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='ISBN',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dept', models.CharField(default='Null', max_length=5)),
                ('des', models.TextField(max_length=300)),
                ('pdf', models.FileField(upload_to='PG')),
                ('points', models.IntegerField(default='0')),
                ('pointsaward', models.IntegerField(default='0')),
                ('user', models.CharField(default='AnonymousUser', max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Patents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dept', models.CharField(default='Null', max_length=5)),
                ('des', models.TextField(max_length=300)),
                ('pdf', models.FileField(upload_to='ThreeClear')),
                ('points', models.IntegerField(default='0')),
                ('pointsaward', models.IntegerField(default='0')),
                ('user', models.CharField(default='AnonymousUser', max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Received',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('des', models.TextField(max_length=300)),
                ('pdf', models.FileField(upload_to='Competitive')),
                ('points', models.IntegerField(default='0')),
                ('pointsaward', models.IntegerField(default='0')),
                ('user', models.CharField(default='AnonymousUser', max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='RIP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dept', models.CharField(default='Null', max_length=5)),
                ('des', models.TextField(max_length=300)),
                ('pdf', models.FileField(upload_to='Innovations')),
                ('points', models.IntegerField(default='0')),
                ('pointsaward', models.IntegerField(default='0')),
                ('user', models.CharField(default='AnonymousUser', max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='RNP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dept', models.CharField(default='Null', max_length=5)),
                ('des', models.TextField(max_length=300)),
                ('pdf', models.FileField(upload_to='UG')),
                ('points', models.IntegerField(default='0')),
                ('pointsaward', models.IntegerField(default='0')),
                ('user', models.CharField(default='AnonymousUser', max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='SCI',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dept', models.CharField(default='Null', max_length=5)),
                ('des', models.TextField(max_length=300)),
                ('pdf', models.FileField(upload_to='Academics')),
                ('points', models.IntegerField(default=0)),
                ('pointsaward', models.IntegerField(default='0')),
                ('user', models.CharField(default='AnonymousUser', max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='SubjectExpert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dept', models.CharField(default='Null', max_length=5)),
                ('des', models.TextField(max_length=300)),
                ('pdf', models.FileField(upload_to='Prizes')),
                ('points', models.IntegerField(default='0')),
                ('pointsaward', models.IntegerField(default='0')),
                ('user', models.CharField(default='AnonymousUser', max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='WOS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dept', models.CharField(default='Null', max_length=5)),
                ('des', models.TextField(max_length=300)),
                ('pdf', models.FileField(upload_to='Internship')),
                ('points', models.IntegerField(default='0')),
                ('pointsaward', models.IntegerField(default='0')),
                ('user', models.CharField(default='AnonymousUser', max_length=300)),
            ],
        ),
    ]
