# Generated by Django 3.0.2 on 2020-03-18 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Academics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academics',
            name='points',
            field=models.IntegerField(),
        ),
    ]
