# Generated by Django 3.0.2 on 2020-03-18 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Academics', '0010_auto_20200318_1956'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Academics',
        ),
    ]
