# Generated by Django 3.0.2 on 2020-03-19 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Academics', '0013_auto_20200319_2127'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Feedback',
        ),
    ]
