# Generated by Django 3.0.2 on 2020-03-20 04:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Academics', '0017_auto_20200319_2152'),
    ]

    operations = [
        migrations.RenameField(
            model_name='innovation',
            old_name='pdf',
            new_name='pdf2',
        ),
    ]
