# Generated by Django 3.0.2 on 2020-03-20 04:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Academics', '0018_auto_20200320_0958'),
    ]

    operations = [
        migrations.RenameField(
            model_name='innovation',
            old_name='pdf2',
            new_name='pdf',
        ),
    ]
