# Generated by Django 3.0.2 on 2020-03-20 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Academics', '0019_auto_20200320_1005'),
    ]

    operations = [
        migrations.AddField(
            model_name='academics',
            name='dept',
            field=models.CharField(default='Null', max_length=5),
        ),
    ]
