# Generated by Django 3.0.2 on 2020-03-20 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Academics', '0020_academics_dept'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='dept',
            field=models.CharField(default='Null', max_length=5),
        ),
        migrations.AddField(
            model_name='innovation',
            name='dept',
            field=models.CharField(default='Null', max_length=5),
        ),
    ]
