# Generated by Django 3.0.2 on 2020-03-20 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Academics', '0021_auto_20200320_1203'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='des1',
            new_name='des',
        ),
        migrations.RenameField(
            model_name='feedback',
            old_name='pdf1',
            new_name='pdf',
        ),
        migrations.RenameField(
            model_name='feedback',
            old_name='points1',
            new_name='points',
        ),
        migrations.RenameField(
            model_name='feedback',
            old_name='pointsaward1',
            new_name='pointsaward',
        ),
        migrations.RenameField(
            model_name='feedback',
            old_name='user1',
            new_name='user',
        ),
    ]
