# Generated by Django 3.0.2 on 2020-03-20 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Academics', '0023_auto_20200320_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academics',
            name='pdf',
            field=models.FileField(upload_to='upload/Academics'),
        ),
        migrations.AlterField(
            model_name='allclear',
            name='pdf',
            field=models.FileField(upload_to='upload/Allclear'),
        ),
        migrations.AlterField(
            model_name='article',
            name='pdf',
            field=models.FileField(upload_to='upload/Article'),
        ),
        migrations.AlterField(
            model_name='awards',
            name='pdf',
            field=models.FileField(upload_to='upload/Awards'),
        ),
        migrations.AlterField(
            model_name='competitive',
            name='pdf',
            field=models.FileField(upload_to='upload/Competitive'),
        ),
        migrations.AlterField(
            model_name='extracurricular',
            name='pdf',
            field=models.FileField(upload_to='upload/Extracurricular'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='pdf',
            field=models.FileField(upload_to='upload/Feedback'),
        ),
        migrations.AlterField(
            model_name='innovation',
            name='pdf',
            field=models.FileField(upload_to='upload/Innovations'),
        ),
        migrations.AlterField(
            model_name='internship',
            name='pdf',
            field=models.FileField(upload_to='upload/Internship'),
        ),
        migrations.AlterField(
            model_name='onlinecertification',
            name='pdf',
            field=models.FileField(upload_to='upload/OnlineCertification'),
        ),
        migrations.AlterField(
            model_name='pg',
            name='pdf',
            field=models.FileField(upload_to='upload/PG'),
        ),
        migrations.AlterField(
            model_name='prizes',
            name='pdf',
            field=models.FileField(upload_to='upload/Prizes'),
        ),
        migrations.AlterField(
            model_name='startups',
            name='pdf',
            field=models.FileField(upload_to='upload/Startups'),
        ),
        migrations.AlterField(
            model_name='studentactivities',
            name='pdf',
            field=models.FileField(upload_to='upload/StudentActivities'),
        ),
        migrations.AlterField(
            model_name='threeclear',
            name='pdf',
            field=models.FileField(upload_to='upload/ThreeClear'),
        ),
        migrations.AlterField(
            model_name='ug',
            name='pdf',
            field=models.FileField(upload_to='upload/UG'),
        ),
    ]
