# Generated by Django 3.0.2 on 2020-03-20 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Academics', '0024_auto_20200320_2319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academics',
            name='pdf',
            field=models.FileField(upload_to='Academics'),
        ),
        migrations.AlterField(
            model_name='allclear',
            name='pdf',
            field=models.FileField(upload_to='Allclear'),
        ),
        migrations.AlterField(
            model_name='article',
            name='pdf',
            field=models.FileField(upload_to='Article'),
        ),
        migrations.AlterField(
            model_name='awards',
            name='pdf',
            field=models.FileField(upload_to='Awards'),
        ),
        migrations.AlterField(
            model_name='competitive',
            name='pdf',
            field=models.FileField(upload_to='Competitive'),
        ),
        migrations.AlterField(
            model_name='extracurricular',
            name='pdf',
            field=models.FileField(upload_to='Extracurricular'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='pdf',
            field=models.FileField(upload_to='Feedback'),
        ),
        migrations.AlterField(
            model_name='innovation',
            name='pdf',
            field=models.FileField(upload_to='Innovations'),
        ),
        migrations.AlterField(
            model_name='internship',
            name='pdf',
            field=models.FileField(upload_to='Internship'),
        ),
        migrations.AlterField(
            model_name='onlinecertification',
            name='pdf',
            field=models.FileField(upload_to='OnlineCertification'),
        ),
        migrations.AlterField(
            model_name='pg',
            name='pdf',
            field=models.FileField(upload_to='PG'),
        ),
        migrations.AlterField(
            model_name='prizes',
            name='pdf',
            field=models.FileField(upload_to='Prizes'),
        ),
        migrations.AlterField(
            model_name='startups',
            name='pdf',
            field=models.FileField(upload_to='Startups'),
        ),
        migrations.AlterField(
            model_name='studentactivities',
            name='pdf',
            field=models.FileField(upload_to='StudentActivities'),
        ),
        migrations.AlterField(
            model_name='threeclear',
            name='pdf',
            field=models.FileField(upload_to='ThreeClear'),
        ),
        migrations.AlterField(
            model_name='ug',
            name='pdf',
            field=models.FileField(upload_to='UG'),
        ),
    ]
