# Generated by Django 3.0.2 on 2020-03-21 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Academics', '0025_auto_20200320_2322'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StudentActivities',
        ),
    ]
